---
title: "SMB_HYBRID_DETECTIVE"
author: "Joe Gunn"
date: "7/10/2020"
output: html_document
---

## Libraries needed for analysis
```{r}
library(genepopedit)
library(parallelnewhybrid)
library(hybriddetective)
library(readxl)
library(tidyverse)
```

## Get top 200 diagnostic loci
```{r}
#Expore genepop data using genepopedit package
genepop_detective("../../raw_data/genepop_data/hsyc_white_pure_genepop.txt", variable = "PopNum")
genepop_detective("../../raw_data/genepop_data/hsyc_white_pure_genepop_2pop.txt", variable = "PopNum")
genepop_detective("../../raw_data/genepop_data/hsyc_skia_pure_genepop.txt", variable = "PopNum")
genepop_detective("../../raw_data/genepop_data/hsyc_skia_pure_genepop_2pop.txt", variable = "PopNum")
genepop_flatten("../../raw_data/genepop_data/hsyc_white_pure_genepop_biall_2pop.txt")
genepop_flatten("../../raw_data/genepop_data/hsyc_skia_pure_genepop.txt")
genepop_flatten("../../raw_data/genepop_data/hsyc_skia_pure_genepop_biall_2pop.txt")
genepop_flatten("../../../../../../hsyc_skia_200_panel_genepop_2pop_full.txt")
genepop_flatten("../../../../../../hsyc_white_200_panel_genepop_2pop_full.txt")


#create a dataframe to designate two different populations (Pure Neosho, Pure Northern)
pop_rename_white <- data.frame(Opop = c("","","","","","","","","","","","","","","","","",""), Rename = c("HSYC","HSYC","HSYC","HSYC","HSYC","HSYC","HSYC","HSYC","WHITE","WHITE","WHITE","WHITE","WHITE","WHITE","WHITE","WHITE","WHITE","WHITE"))

pop_rename_skia <- data.frame(Opop = c("","","","","","","","","","","","",""), Rename = c("HSYC","HSYC","HSYC","HSYC","HSYC","HSYC","HSYC","HSYC","SKIA","SKIA","SKIA","SKIA","SKIA"))

#Designate the two different populations (Pure Neosho, Pure Northern)
subset_genepop_rename("../../raw_data/genepop_data/hsyc_white_200_panel_genepop_full.txt", pop_rename_white, path = "/Users/joegunn/Desktop/hsyc_white_200_panel_genepop_2pop_full.txt")

subset_genepop_rename("../../raw_data/genepop_data/hsyc_skia_200_panel_genepop_full.txt", pop_rename_skia, path = "/Users/joegunn/Desktop/hsyc_skia_200_panel_genepop_2pop_full.txt")

#Run command to extract the top 200 diagnositic SNPs (with highest Fst values) across pure Neosho and Northern populations. Both PGDSpider and PLINK needed to be installed on my local computer, and the respective paths to both executables are given in this function. 

#Get panel SNP panel for Skiatook lake and Honey Syc populations
getTopLoc(GPD = "/Users/joegunn/Desktop/Grad_School_Stuff/Research/Projects/Smallmouth_Bass_Genomics/raw_data/genepop_data/hsyc_skia_pure_genepop_biall_2pop.txt", panel.size = 200,
where.PGDspider = "/Users/joegunn/Downloads/PGDSpider_2.1.1.5/", where.PLINK = "/Users/joegunn/Downloads/plink_mac_20200616/")

#Get panel SNP panel for White and Honey Syc populations
getTopLoc(GPD = "/Users/joegunn/Desktop/Grad_School_Stuff/Research/Projects/Smallmouth_Bass_Genomics/raw_data/genepop_data/hsyc_white_pure_genepop_biall_2pop.txt", panel.size = 200,
where.PGDspider = "/Users/joegunn/Downloads/PGDSpider_2.1.1.5/", where.PLINK = "/Users/joegunn/Downloads/plink_mac_20200616/")
```

## Simulate multigenerational hybrids 
```{r}
freqbasedsim_AlleleSample(GPD = "/Users/joegunn/Desktop/Grad_School_Stuff/Research/Projects/Smallmouth_Bass_Genomics/raw_data/genepop_data/hsyc_skia_pure_genepop_biall_2pop_200_Loci_Panel.txt", NumSims = 3, NumReps = 3)

```

## Determine the SNP names for the 200 diagnostic SNPs discovered in the above analyses - this is necessary, because the hybriddetective workflow code just generates the number of the SNPs that were used to make the panel (SNP_1, 2, 3, etc.) rather than the actual SNP name.
```{r}
snp_metadata <- read_excel("../../metadata/smb_snp_metadata.xlsx")
snp_metadata <- snp_metadata %>%
  mutate(snp_number = factor(snp_number))

#Honey Creek and Sycamore Creek with the White River SNPs
hsyc_white_200_panel_snps <- read_excel("../../metadata/hsyc_white_200_panel.xlsx")
hsyc_white_200_panel_snps <- hsyc_white_200_panel_snps %>%
  mutate(snp_number = factor(snp_number))

hsyc_white_200_panel_snp_names <- merge(snp_metadata, hsyc_white_200_panel_snps, by = "snp_number")

#Honey Creek and Sycamore Creek with Skiatook Lake SNPs
hsyc_skia_200_panel_snps <- read_excel("../../metadata/hsyc_skia_200_panel.xlsx")
hsyc_skia_200_panel_snps <- hsyc_skia_200_panel_snps %>%
  mutate(snp_number = factor(snp_number))

hsyc_skia_200_panel_snp_names <- merge(snp_metadata, hsyc_skia_200_panel_snps, by = "snp_number")

#Write out tables with SNP names to be kept for hybrid analysis - these will be text files that can be later used in vcftools to subset vcfs on Lewis 
write.table(hsyc_white_200_panel_snp_names,"~/Desktop/Grad_School_Stuff/Research/Projects/Smallmouth_Bass_Genomics/metadata/hsyc_white_200_panel_snp_names.txt", sep="\t")

write.table(hsyc_skia_200_panel_snp_names,"~/Desktop/Grad_School_Stuff/Research/Projects/Smallmouth_Bass_Genomics/metadata/hsyc_skia_200_panel_snp_names.txt", sep="\t")
```